Stage1
AnastasiyaC/webix-jet-test pull request #1
Opened 2022-04-25 16:06 UTC by AnastasiyaC

codebase оставила для Оли, она просила

2022-04-25 17:18 UTC, kullias commented
линт не проходит
![Selection_999(832)](https://user-images.githubusercontent.com/31205423/165140354-57b43ebd-95bf-40f6-9a49-be44c1c928d8.png)

2022-04-25 17:25 UTC, kullias commented
на маленьких экранах печаль
![Selection_999(833)](https://user-images.githubusercontent.com/31205423/165141383-51e40727-e594-4e19-914a-90b2d9fb148a.png)

2022-04-25 17:38 UTC, kullias commented
> codebase оставила для Оли, она просила

эх, то ли мой интернет, то ли гитхаб этого не вынес и смотреть изменения тут не выходит, тупо не грузятся многие файлы

у меня есть немного сомнения: а пулл реквест был готов к проверке? я назначила ревьюров, думая, что мб ты забыла, но щас смотрю у меня все операции 404 кидают и как-то даже потестировать не выходит. щас посмотрю в чем дело, интересно
мб тут что-то еще не готово?

2022-04-25 17:45 UTC, kullias commented
> > codebase оставила для Оли, она просила
> 
> эх, то ли мой интернет, то ли гитхаб этого не вынес и смотреть изменения тут не выходит, тупо не грузятся многие файлы
> 
> у меня есть немного сомнения: а пулл реквест был готов к проверке? я назначила ревьюров, думая, что мб ты забыла, но щас смотрю у меня все операции 404 кидают и как-то даже потестировать не выходит. щас посмотрю в чем дело, интересно мб тут что-то еще не готово?

с твоего клиента запросы идут на урл с каким-то странным сегментом: http://localhost:8096/api/v1/activities/%20/98 - `%20` быть не должно

2022-04-25 18:18 UTC, kullias commented on sources/models/activityTypes.js
> +			obj.value = obj.Value;
но с фильтром все же что-то не так
![Selection_999(837)](https://user-images.githubusercontent.com/31205423/165149726-daf4f687-2b8b-484d-863f-2eb9c6a6c820.png)

2022-04-25 19:18 UTC, kullias requested changes

2022-04-25 19:18 UTC, kullias commented on sources/models/activityTypes.js
> +			obj.value = obj.Value;
и с контактами тоже, там тоже айдишки отображаются в списке

2022-04-25 19:18 UTC, kullias commented on sources/myapp.js
> +			webix.delay(() => webix.message(`Catch error: ${err}`));
для (воображаемого) конечного пользователя не очень решение
лучше перенаправить чела на существующую страницу

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +					sort: "date",
каждый 2-ой клик по хедеру ничего не делает
вероятно потому что поле со строковыми данными
надо либо свой сортировщик написать что будет даты объекты из строк добывать, но лучше в схеме завести поле с датой-объектом и сюда его

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		if (idParam) return;
if (!idParam) datatable.unselectAll();

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +			this.setParam("id", idParam, true);
после удаления этот парам не убирается
в итоге если страница обновится, эта штука кидает ошибку при попытке селекта

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +			this.setParam("id", idParam, true);
надо либо тут проверять на существование, либо по удалению парам чистить

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +							content: "datepickerFilter"
в теперешнем состоянии не находит записи с датами, где время ненулевое
надо вероятно compare ему переопределить

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesForm.js
> +							template: "#Value#"
в коллекции в схеме поле там создавалось value. по идее должно было хватить и тут, и фильтру
не сработало?

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesForm.js
> +				TypeID: webix.rules.isChecked,
хм. оно позиционируется для чекбокса, для комбо  вообще лучше  isNotEmpty наверное

2022-04-25 19:18 UTC, kullias commented on sources/views/contactsViews/contactInfo.js
> +				const infoDetails = infoTotal.join(",").replace(/,/g, "");
join("")

2022-04-25 19:18 UTC, kullias commented on sources/views/contactsViews/contactsList.js
> +		if (idParam) return;
if (!idParam) list.unselectAll();

2022-04-25 19:18 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.activitiesForm = new ActivitiesForm(this.app);
инитить боди окна отдельно от окна и потом отдельно с ними работать - это очень нестандартное решение
по сравнению со стандартным, оно объемное, сложновато воспринимается сходу и вероятно сложновато поддерживается в перспективе

каноничное решение тут, если делить на 2 класса - передавать класс формы классу окна и не инитить форму самостоятельно
и если что-то извне надо форме передать от другого вью, делать это тоже через окно (например, окно получает айди или не получает, и по этому оно решает, это будет редактирование или добавление)
вообще поскольку тут уже есть параметр урла с айдишкой, тут даже ничего ни окну, ни форме передавать не надо. они могут получить доступ к этому параму сами и сами себе порешать, что за операция, какие лейблы...

еще там в форме видела вызываются методы окна
безопаснее через события
методы по канону используются для коммуникации родитель->дитя (статическое!)
события - дитя->родитель (и прочие безысходные кейсы, когда урл парамы не катят)

2022-04-26 10:01 UTC, olimed commented on sources/views/activitiesViews/activitiesDatatable.js
> +						return activityValue;
можешь сократить: `return activityType?.Value || "activity not found" `

2022-04-26 10:01 UTC, olimed commented on sources/views/activitiesViews/activitiesDatatable.js
> +						const contactValue = contact ? `${contact.FirstName} ${contact.LastName}` : "contact not found";
так как в коллекции ты создавала свойство `value` с firstName and LastName, то можешь: `contact.value`

2022-04-26 15:35 UTC, olimed commented on sources/views/activitiesViews/activitiesDatatable.js
> +			datatable.select(idParam);
в init() такая же логика, можешь в отдельный метод вынести

2022-04-26 15:35 UTC, olimed commented on sources/views/activitiesViews/activitiesForm.js
> +							template: "#value#"
так как в коллекциях уже есть значения с ключом value, то template не обязательно указывать

2022-04-26 16:56 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.activitiesForm = new ActivitiesForm(this.app);
в какой-то момент при обновлении записи валится ошибка про некорректный айди
я то добавляла, то обновляла активити, и на очередном обновлении после добавления
![Selection_999(851)](https://user-images.githubusercontent.com/31205423/165353031-eed38afe-f732-46cd-9783-5841e2924cdf.png)

2022-04-26 16:58 UTC, kullias commented
после add, update, delete в таблице активити стоит восстанавливать фильтрацию. иначе сейчас если что-то изменить в данных после того, как фильтры были выставлены, фильтрация сбросится, а фильтры нет

2022-04-26 17:02 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.activitiesForm = new ActivitiesForm(this.app);
из странного с формой еще заметно что при первом открытии для add дата и время заполняется, а дальше нет. должно быть постоянство (или так или так), непостоянство в поведении в одном и том же кейсе на какой-то баг намекает

2022-04-26 17:22 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.windowForm = this.ui(new ModalWindowViewCenter(this.app, ActivitiesForm, "Add activity.", {width: 600}));
не, не надо форму так передавать
форму надо импортировать в модуль окна

2022-04-26 17:23 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.windowForm = this.ui(new ModalWindowViewCenter(this.app, ActivitiesForm, "Add activity.", {width: 600}));
насчет ширины - а она разная в зависимости от того, зачем окно открывается? визуально одинаковые

2022-04-26 17:35 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.windowForm.showWindow(1, "Add activity.");
единицу лучше не добавлять, она может быть реальной айдишкой
ноль я предлагала с той т.з. что в вебиксе не могут айдишки быть нулями
но еще надежнее будет что-то типа $temp, $new или другое в таком духе

2022-04-26 17:35 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		webix.Date.equal(value, filter);
return?

2022-04-26 17:55 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
>  		this.windowForm.showWindow(id, "Edit activity.");
так а строку с лейблом для хедера тоже можно не передавать. тоже по айди решать

2022-04-26 17:56 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
>  		this.windowForm.showWindow(id, "Edit activity.");
чем меньше можно передавать параметров классу в его методы и чем больше класс сам своей логикой управляет, тем лучше.

2022-04-26 18:06 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +			datatable.parse(activitiesCollection);
а зачем ты по каждому урл чейнджу данные в таблице парсишь заново?

2022-04-26 18:11 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.setIdParam();
у этого метода несколько сбивающее с толку название
метод парсит данные в таблицу, считывает параметр из урла, если его нет вызывает перерисовку, если есть делает селект и сеттит параметр в урл. много что делает

кстати, а зачем эта штука с параметром в таком порядке?

2022-04-27 09:25 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +		this.windowForm.showWindow("");
можно пустую строку не передавать, можно ничего не передавать

2022-04-27 10:12 UTC, kullias approved these changes

2022-04-27 10:12 UTC, olimed approved these changes

2022-04-27 10:12 UTC, merged