Stage2
AnastasiyaC/webix-jet-test pull request #2
Opened 2022-05-05 16:22 UTC by AnastasiyaC

2022-05-05 21:03 UTC, olimed reviewed
1) этот пункт в задании не выполнен (после добавления контакта, в листе выбирается первый, а так же после нажатия на кнопку  cancel)
![image](https://user-images.githubusercontent.com/31127246/167021580-8a41dab5-4ee6-4bf5-bc5a-782b12770d1b.png)
2) небольшой баг:
![2326](https://user-images.githubusercontent.com/31127246/167021753-f3fda578-9bae-4549-8d98-fdbfa0361341.gif)
3) после удаления контакта с activity, их стоит убирать из списка 
![image](https://user-images.githubusercontent.com/31127246/167022091-73ae76d3-5511-449d-8e0b-2618e9986b41.png)
4) сортировка файлов по дате работает через раз
5) ещё небольшой баг:
![2350](https://user-images.githubusercontent.com/31127246/167023454-61471694-1494-4936-82ff-4c501ff271a2.gif)
     а) если после этого попробовать редактировать, то открывается форма с пустыми полями и заголовком Edit
     б) если пробовать удалять, но будет показан confirm, а пользователь никакой не удалится
6) если у тебя есть модули, которые ты переиспользуешь, то лучше их выносить в отдельную папку, например, папку components/modules.

2022-05-05 21:03 UTC, olimed commented on sources/views/activitiesViews/ActivitiesModalWindow.js
> +			this.setParam("aid", "0", true);
1)  такие сокращения как `a, b, c, ...` лучше не использовать, не очень понятно, для каких целей используется та или иная переменная, аналогично и для названий параметров. В данном случае, можно использовать `activityId`  
2) айдишка равная `"0"` мало вероятно, но может быть, поэтому не стоит сетить значение, лучше удалить этот параметр из урла

2022-05-05 21:03 UTC, olimed commented on sources/views/activitiesViews/activitiesDatatable.js
> +			this._setNameValueToForm = this._hiddenColumn === "ContactID";
для чего это переменная?

2022-05-05 21:03 UTC, olimed commented on sources/views/contacts/contactForm.js
> +		webix.promise.all([
не нужно каждый раз загружать коллекции при изменении урла, лучше вынести это в init()

2022-05-05 21:03 UTC, olimed commented on sources/views/contacts/contactForm.js
> +			label: this._editMode === "add" ? "Add new contact" : "Edit contact",
нет смысла в этой проверке, потому что ты в конструкторе задаешь значение

2022-05-05 21:03 UTC, olimed commented on sources/views/contacts/contactForm.js
> +				label: this._editMode === "add" ? "Add" : "Save",
тоже самое, так как ты уже задала значение переменной this._editMode, то можно не проверять его здесь

2022-05-06 11:29 UTC, kullias requested changes

2022-05-06 11:29 UTC, kullias commented on sources/models/contacts.js
> +			obj.BirthdayDate = webix.i18n.longDateFormatStr(obj.Birthday);
а это поле только в темплейте в инфо используется для отображения?
в принципе можно прям там и форматировать, но наверное не так критично

2022-05-06 11:29 UTC, kullias commented on sources/views/activitiesViews/ActivitiesModalWindow.js
> +			this.setParam("aid", "0", true);
да, ты права. извините, это я посоветовала назвать aid и cid их, просто чтобы они вообще по-разному назывались, а не везде id. но да, лучше называть максимально понятно и полно, так и есть

2022-05-06 11:29 UTC, kullias commented on sources/views/contacts/contactFiliesDatatable.js
> +		savedFile.ChangeDate = dateFormat(savedFile.ChangeDate);
не надо. у тебя уже есть формат в колонке для правильного отображения, а данные пусть остаются объектом
логика вебикса, которая заточена под работу с датами, чаще всего ждет объект

2022-05-06 11:29 UTC, kullias commented on sources/views/contacts/contactForm.js
> +		this.setFormValues();
есть баг:
- нажимаешь Edit для контакта
- потом сразу нажимаешь Add contact
- вроде как форма перевелась в add режим, но данные не очистились
- нажимаешь Save - ошибка
![Screenshot from 2022-05-06 14-01-25](https://user-images.githubusercontent.com/31205423/167119572-6d573f2f-3639-4e6b-865d-dfc5758785d6.png)

- этот айтем тем не менее реально будто бы добавился, его можно пытаться селектить, и каждый разу будет кидать ошибку (пока не обновишь страницу)
![Screenshot from 2022-05-06 14-03-16](https://user-images.githubusercontent.com/31205423/167119823-d4df9f20-7845-44ff-bc6e-3c6d8e52b864.png)

2022-05-06 11:29 UTC, kullias commented on sources/views/contacts/contactForm.js
> +			label: this._editMode === "add" ? "Add new contact" : "Edit contact",
кажется в конструкторе оно вообще и не надо, там ниже по-любому сеттится лейбл по урл чейнджу

2022-05-06 11:29 UTC, kullias commented on sources/views/activitiesViews/activitiesDatatable.js
> +			if (contactId) this.filterByContactName(contactId);
не хватает этой фильтрации после применения встроенных фильтров
как проявляется:
- пофильтруй по типу активити
- сбросится фильтр по контакту

есть у таблицы событие onAfterFilter, которое срабатывает именно после фильтрации по встроенным фильтрам, и вот в такое событие стоит добавить вызов фильтрации по контакту

2022-05-06 11:29 UTC, kullias commented on sources/views/contacts/index.js
> +		this.on(this.app, "openContactInfo", id => this.show(`./contacts.contactInfo?cid=${id}`));
1 и 4 могли бы быть одним ивентом
2 и 3 тоже могли бы быть одним ивентом

типа openInfo с айди или без
и openForm с айди или без

2022-05-06 11:29 UTC, kullias commented on sources/views/contacts/index.js
> +		this.on(this.app, "openContactInfo", id => this.show(`./contacts.contactInfo?cid=${id}`));
чем меньше ивентов, тем менее запутанная их система

2022-05-10 10:15 UTC, olimed reviewed
остался баг: при удалении контакта его activities остаются в таблице

2022-05-10 10:15 UTC, olimed commented on sources/views/commonViews/activitiesForm.js
> +			this.setFormValues();
наверное, нет особого смысла на `init() ` вызывать этот метод, потому что форму ты заполняешь при открытии окна

2022-05-10 10:15 UTC, olimed commented on sources/views/commonViews/activitiesForm.js
> +			this.showCurrentPage();
код дублируется в методе toggleCancel(). в этом месте просто можно вызвать метод `this.toggleCancel()`

2022-05-10 10:15 UTC, olimed commented on sources/views/commonViews/activitiesModalWindow.js
> +		this.app.callEvent("setFormValue");
это событие стоит вызывать, когда нет id. Иначе в форме срабатывает 2 раза метод setFormValues() ( на urlChange и после вызова этого события)

2022-05-10 11:47 UTC, olimed approved these changes

2022-05-10 11:48 UTC, kullias commented on sources/views/commonViews/activitiesForm.js
> +		const params = this.getUrl()[0].params;
getParam("cid", true) было б надежнее, чем лезть в урл
есть какая-то причина тут так делать?

2022-05-10 11:48 UTC, kullias commented on sources/views/commonViews/activitiesForm.js
> +		const params = this.getUrl()[0].params;
см коммент выше

2022-05-10 11:48 UTC, kullias commented on sources/views/commonViews/activitiesForm.js
> +			const dateAndTime = new Date(item.DueDate);
а зачем делать копию, если в оба контрола потом идет одна и та же? что-то ломалось без копирования?
я бы думала, что копию стоит сделать, чтоб в контролы разные даты пошли, но мб есть какая-то причина

2022-05-10 11:48 UTC, kullias commented on sources/views/contacts/contactForm.js
> +			this.setFormValues();
сразу после него сработает урл чейндж и этот же метод вызовется там
этот вызов в ините наверное не нужен

2022-05-10 11:48 UTC, kullias commented on sources/views/contacts/contactForm.js
> +		this.setFormValues();
ошибку не кидает, все данные чистятся, кроме фотки. фотку осталось зачистить для такого кейса

2022-05-10 11:48 UTC, kullias commented on sources/views/contacts/contactsList.js
> +				list.unselectAll();
а на это какая-то зависимая логика полагается? просто если в листе нету ничего, то ничего у него и не селектнуто (при удалении логика вебикса зачищает селект сама)

2022-05-10 17:57 UTC, kullias approved these changes

2022-05-10 17:57 UTC, merged