feat: add settings, filters to contacts and activities
AnastasiyaC/webix-jet-test pull request #3
Opened 2022-05-12 22:59 UTC by AnastasiyaC

2022-05-13 11:36 UTC, kullias requested changes

2022-05-13 11:36 UTC, kullias commented on sources/myapp.js
> +		app.use(plugins.Locale);
вебиксовую локаль тоже надо https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/plugins#combining-with-webix-locales

2022-05-13 11:36 UTC, kullias commented on sources/views/commonViews/activitiesDatatable.js
> +			if (tabId === "Completed") {
2 раза

2022-05-13 11:36 UTC, kullias commented on sources/views/commonViews/activitiesDatatable.js
> +			if (tabId === "Completed") {
я недавно буквально встретила красивый способ, как в этом колбэке избавиться от кучи проверок (ведь в худшем случае каждый айтем пройдет их все):

- создать объект со всеми фильтрами

```js
const filters = {
  Completed: obj => obj.State === "Close",
  // ... etc
};
```
- потом вызвать фильтрацию

```js
table.filter(filters[tabId], null, true);
```

прим: дополнительный третий параметр тебе скорее всего понадобится, чтобы не сбрасывалась фильтрация по встроенным фильтрам

помимо отсутствия проверок, плюс такого подхода еще и в том, что заодно обрабатывается кейс, когда нужно сбросить фильтрацию. table.filter() вызовется тогда без параметров, а значит не будет прохода по всем данным с этим колбэком

2022-05-13 11:36 UTC, kullias commented on sources/locales/en.js
> +	"incomplete form": "Form is incomplete. Fill the form!",
мы на вебиксе пришли к мнению, что мы против ситуации, когда ключи локалей не совпадают с реально отображаемыми лейблами, потому что если сломается локаль или не будет перевода, вместо полного читабельного лейбла на хоть каком-то языке будет отображаться краткий ключ. у тебя тут они не такие и плохие (иногда я встречала что-то типа btnLabel), но все равно лучше, чтоб они совпадали.
дополнительный аргумент - проще добавлять новые локали, когда в ключах полная фраза. иначе придется смотреть на другие локали, и хорошо, если знаешь язык. а если нет - это дополнительная проблема для того, кто переводит

2022-05-13 11:36 UTC, kullias commented on sources/views/contacts/contactForm.js
> +		this.app.callEvent("onEnableListFilter");
обычно события называются в честь того, что произошло, а не в честь того, что надо сделать. в общем касается и события по прошлому стейджу. когда события называются именно так, проще разбираться в системе событий.

здесь у нас клик по кнопке cancel, то есть событие можно назвать onFormCancel
и вот уже все те вьюхи, которым надо на это событие отреагировать, будут выполнять по нему свои действия (у кого-то это селект в листе, у кого-то показ инфо, у кого-то фильтрация в листе)

я бы пересмотрела всю систему событий и привела ее вот так в порядок. таким образом тут вообще останется только 1 событие, которое будет передавать contactId или нет, и в зависимости от этого будет показываться инфо или же делаться селект и показываться инфо, и будет запускаться фильтрация в листе

остальные случаи по аналогии

2022-05-13 11:36 UTC, kullias commented on sources/views/contacts/contactsList.js
> +		const value = listFilter.getValue().toLowerCase();
стоит проверить, не пустая ли там строка, и если пустая - просто сразу вызвать list.filter() - без параметров.
когда ты вызываешь фильтрацию без параметров, лист сразу вызывает рефреш и все
если с параметрами - сначала выполняется проход по всем айтемам с колбэком (зря почем) и только потом рефреш.

2022-05-13 11:36 UTC, kullias commented on sources/views/commonViews/activitiesDatatable.js
>  		this.on(datatable, "onAfterFilter", () => this.filterByContactName());
после дата операций и применения встроенных фильтров сбивается фильтрация по таббару
потому:
- по дата операциям и по смене таба стоит вызывать filterByAll
- в обработчике onAfterFilter вызывать и фильтрацию по контакту, и фильтрацию по табу (не забывая в обоих случаях про третий параметр true, чтоб не сбивать предыдущие фильтры

2022-05-13 11:41 UTC, kullias commented on sources/locales/ru.js
> +	"Type to find contact": "Поис подходящего контакта",
опечаточка

2022-05-16 07:03 UTC, olimed commented on sources/views/commonViews/activitiesDatatable.js
> +	filterByTabFilterName(tabId) {
1) так как в tabId ты передаешь `this._tabId`, то можно не передавать ( но это не критично)
2) но на наличие значения, лучше проверять, потому что `this._tabId` может быть undefined

2022-05-16 07:03 UTC, olimed commented on sources/views/commonViews/activitiesForm.js
> +			webix.message(_("incomplete form"));
такого сообщения нет в переводах

2022-05-16 10:45 UTC, kullias commented on sources/utils/activitiesFilters.js
> +	All: () => true,
стоит убрать, это как с пустой строкой из инпута
вызовется table.filter(undeinfed, null, true) и скинет фильтрацию без прохода с колбэком (от прохода нет смысла, но лишняя работа), просто вызвав рефреш

2022-05-16 10:54 UTC, kullias approved these changes

2022-05-16 11:06 UTC, olimed approved these changes

2022-05-16 11:06 UTC, merged